services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../chest_Xray:/app/chest_Xray:ro
      - ../checkpoints:/app/checkpoints:ro
      - ../exports:/app/exports:ro
      - ../configs:/app/configs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PYTHONPATH=/app

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns
    environment:
      - MLFLOW_ALLOW_FILE_STORE=true
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns
